### ISSUE TITLE
Constant Bitrate ignores given Target Bitrate and Filler Data constraints.

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#18]
For an unknown reason, AMF currently fails to properly meet the given Target Bitrate on a number of cards. Mostly affected by this are VCE3.x based cards, like the R9 285, R9 380 and the RX 4xx series.

The bitrate will always be lower than needed or be way above the target, which makes streaming hard if not impossible. 

### System Information
* Windows 10 64-Bit (Anniversary Update, automatic Updates enabled)
* CPU: Intel 4690
* Mainboard: GIGABYTE H97-D3H
* GPU: RASUS Radeon R9 285 Strix OC DirectCU II
* Driver: 16.10.3

### 1. Dump Files
- mega.co.nz: https://mega.nz/#!jBcDRZ4R!G8K59-e0pUPFhvyHxNxmMmAcXKYmbpa56ZdEWl1I_Bw
- xaymar.com: http://cdn.xaymar.com/private/2016/09/11-09-2016_obs64.7z

### 2016-11-02 Bitrate Problem returns on R9 285
- Recording (correct Bitrate): http://cdn.xaymar.com/private/2016/11/2016-11-02%2020-35-35.mkv
- Log: http://cdn.xaymar.com/private/2016/11/2016-11-02_20-36-09.txt
- Recording (wrong Bitrate): http://cdn.xaymar.com/private/2016/11/2016-11-02%2020-26-28.mkv
- Log: http://cdn.xaymar.com/private/2016/11/2016-11-02_20-30-43.txt

### 2016-11-03 (20mb/s instead of given 3500kbit/s)
* Log: http://cdn.xaymar.com/private/2016/11/2016-11-03%2018-21-18.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-03_18-21-26.mkv

**Comment by Xaymar** [comment]
It seems that AMF decides to go for a lower overall bitrate in darker areas, instead of increasing the bitrate for those - which leads to drastic quality loss for those areas or games.

I tested out a few changed but none really changed things - it would always either go below target bitrate or above: https://r-1.ch/analyzer/results/xaymar.e34745

**Comment by Xaymar** [comment]
This also applies to Variable Bitrate with a Peak restriction. It will never meet the target bitrate if the frame is too dark or there is little going on.

**Comment by MikhailAMD** [comment]
Variable Bitrate with a Peak restriction works as expected. It will not guarantee to reach target because there is no filler data. 
We confirm that CBR with filler data doesn't work correctly on VCE3. Earlier versions are OK. The fix will be in the driver package and will follow shortly.

**Comment by Xaymar** [comment]
> We confirm that CBR with filler data doesn't work correctly on VCE3.

Does that mean that a R9 290, R7 370 and a RX 480 are all VCE3? Users on these cards have reported the issue to me, which I was able to reproduce on my R9 285 too without any issues.
It's good to see that it can and will be fixed.

**Comment by MikhailAMD** [comment]
check the list here: https://en.wikipedia.org/wiki/Video_Coding_Engine

**Comment by Xaymar** [comment]
Pinging this issue again as it was not fixed in 16.9.2. When can we expect to see a working version?

**Comment by Benman2785** [comment]
Hi - found out that the ONLY non-changeable variable is minQP 1 -> all others can be changed and still uses CBR (even when its not that correct in terms of set bitrate - but has not that "up n down bitrate" behaviour)

**Comment by Xaymar** [comment]
CBR works like a charm in 16.9.2, no issues anymore.

**Comment by MikhailAMD** [comment]
Not so fast. We did find a problem with filler data. The meaningful bits are OK. Please test the upcoming next public driver (hotfix).
Thanks,
Mikhail

**Comment by Xaymar** [comment]
I will once it's out. What should I look out for? Is it a card specific error with Filler Data?

**Comment by MikhailAMD** [comment]
You should see very steady bitrate with CBR on RX480. On black areas or in general on low information areas encoder adds filler data with zeros to the encoded frame. They don’t have meaningful bits but are important for certain streaming types and certain decoders.

Mikhail

**Comment by M4RK22** [comment]
CBR + filler data isn't stable at this moment on my rx480. I'll try the next driver update.

**Comment by Xaymar** [comment]
It seems to have been fixed by 16.10.1 now. Waiting for more reports that it was fixed before closing it again.

**Comment by MikhailAMD** [comment]
Yes, the fix is in. Take your time to verify.

Mikhail
On Wed, Oct 05, 2016 at 3:55pm, Michael Fabian Dirks <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems to have been fixed by 16.10.1 now. Waiting for more reports that it was fixed before closing it again.

-

**Comment by M4RK22** [comment]
Hi, I've noticed some variances in the bitrate going from 8600 to 12000 Kbps when the Bitrate setting is 10000 Kbps CBR + Filler data (RX480). This happen sometimes at the start of the streaming and a few times latter. I don't know if this is a issue but I want to keep you informed. In practice Now I can stream with a stable bitrate.

**Comment by Benman2785** [comment]
@M4RK22 use my settings provided at https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/issues/90 and change to disired bitrate + calculate strict VBV Buffer (bitrate/FPS*10-1 = Buffer)

@MikhailAMD "minQP 1" is still forced when using CBR -> without it the problem still persists in 16.10.1

**Comment by Xaymar** [comment]
There are still reports of RX 4xx having trouble with CBR and Filler Data. Bitrate seems to ignore Filler Data or Target Bitrate at times.

**Comment by MikhailAMD** [comment]
if you want strict flow of the data please set VBV buffer size to bitrate/FPS.
Please verify that users got the latest driver (16.10.1).
The glitches maybe related to the performance issue in CBR we are still investigating. Please note that VBR doesn't have performance issues.

**Comment by Benman2785** [comment]
@MikhailAMD but setting VBV to Bitrate/FPS is "to strict" - better is Bitrate/FPSx10-1 // but i will test it and say if its working

**Comment by Xaymar** [comment]
Only rare cases where fillerdata gets added to the second after the one where it should have been in remain, but those are probably due to encoding stress. I'll close this as resolved on my end.

**Comment by Benman2785** [comment]
when there is no movement and a mostly black screen the FillerData doesnt work properly -> i can upload footage of this

**Comment by Benman2785** [comment]
![3400kbps_fillerdata-bug_persists](https://cloud.githubusercontent.com/assets/21282980/19552101/ad569962-96ae-11e6-8482-2042b7c726bb.jpg)
http://benmanshafen.de/pics/OBS/Xaymar/3400kbps_FillerData-Bug_persists.mp4

here u have video and you see the problem in picture

**Comment by Xaymar** [comment]
Update to the latest 16.10.1, check "Debug Tracing" in the plugin and then
upload a video and log file.

**Comment by Benman2785** [comment]
will be uploaded in 30min

**Comment by Benman2785** [comment]
still persists - and worse -> it PEAKS hard now "to maintain bitrate over time"

![3500kbps_fillerdata-bug_persists](https://cloud.githubusercontent.com/assets/21282980/19556964/e570cc5e-96c3-11e6-948c-e3241d7f9df5.jpg)

[3500kbps_FillerData-Bug_persist_log.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/541483/3500kbps_FillerData-Bug_persist_log.txt)

http://benmanshafen.de/pics/OBS/Xaymar/3500kbps_FillerData-Bug_persists.mp4 (160mb)

**Comment by Xaymar** [comment]
Total still looks okay, it just moved all the data from what should have been there to when it could push them out. Make sure that your system is not overloaded during encoding, as it is the case here.

**Comment by Benman2785** [comment]
what you men with overloaded? i just have 8gb RAM -> will upgrade soon
-
with CBR it shouldnt peak that much - because this will result in dropped frames at twitch or even youtube (when its that high)

so it needs to be fixed

**Comment by Xaymar** [comment]
No it doesn't because it's not a bug. It's your system being overloaded (too slow, too much workload at that time, etc). It has nothing to do with RAM.

**Comment by Benman2785** [comment]
ah - ok -> but that peak doesnt occure in 16.9.2

my cpu loaded new stage of game -> its impossible to avoid that -> so its still a bug
btw its just 60% load on CPU when "no fillerdata bug" was
just peaked to 100% CPU as GPU send "peaked bitrate" into recording
u can watch load of computer in left corner

**Comment by CKannas** [comment]
@Benman2785 are you using the 32-bit version of OBS?
Because is listing only 2GB of ram and OBS Version -> OBS 0.16.2 (windows),
while just looking some logs from my system is states OBS version -> OBS
0.16.2 (64bit, windows).

Tip: You can add the CoreAudio AAC encoder in you OBS by installing some
parts of iTunes google it and you will find how to do it. They say it is
better than windows AAC encoder.

Christos

Christos Kannas

Researcher
Ph.D Student

Mob (UK): +44 (0) 7447700937
Mob (Cyprus): +357 99530608

[image: View Christos Kannas's profile on LinkedIn]
<http://cy.linkedin.com/in/christoskannas>

**Comment by Xaymar** [comment]
I took a look at your video upload:
* Average overall bitrate (including audio) is 3641 kb/s
* Average video bitrate (excluding audio) is 3498 kb/s
* Framerate is 30, Constant

Overall, nothing is wrong with the file or CBR - it did what it should have done.

**Comment by Benman2785** [comment]
@CKannas - i have an different AAC Codec (i think) from dB PowerAMP
i use 32Bit version of OBS because my Webcam has only 32bit driver -> in OBS classic 64bit i had problems with 32bit drivers -> so i stick 2 use 32bit OBS

@Xaymar 
thank you - but i cant believe that a peak of 16000kbps is normal with CBR due to limitations of most bitrate-limited streaming servers
and it adds up bitrate after a scene with no movement and nearly black screen -> it SHOULDNT peak after that (and better use FillerData to avoid that peak)

**Comment by Xaymar** [comment]
You're recording to a file, muxing is different for files than for streaming. Streaming enforces stricter rules, while recording can mux video, audio and whatever however it wants - as long as it's in order.
You shouldn't see this happening while streaming, so you should try streaming first - if it occurs there, then it's a problem.

**Comment by Benman2785** [comment]
i will try streaming now - (on my own server - and tell u then)

**Comment by Benman2785** [comment]
still does that while streaming -> so streaming to most platforms not possible -> because you will have drops

![stream-1476968574](https://cloud.githubusercontent.com/assets/21282980/19561194/e6069892-96d7-11e6-82d7-2b206c00e4f1.jpg)
http://benmanshafen.de/streamdl/stream-1476968574.flv (65mb)

**Comment by Xaymar** [comment]
Try 16.10.2 Hotfix, it might help.

**Comment by Xaymar** [comment]
I took a look at the log file, here is what you're doing wrong:

1. You're using the Advanced Interface, it is not supported.
2. Memory Type is set to DirectX11 without OpenCL Compute Type, this can have severe performance effects.
3. You've changed Maximum Long-Term Reference Frames to 1, keep it at 0.
4. Peak Bitrate is 10000, it is not recommended to override this when using CBR.
5. Minimum QP and Maximum QP are wrong for CBR, Minimum QP should be 0 and Maximum QP 51.
6. GOP Size is set to 15 frames - this is extremely experimental, never change it unless you're prepared to see issues.
7. CABAC has been Enabled - this is extremely experimental, never change it unless you're prepared to see issues.

**Comment by Benman2785** [comment]
1-3 - ok -> will change that
4 - why is that? because peak bitrate is added to "normal" Bitrate nearly all the time -> so it wont work properly when streaming to twitch
5 - minQP 1 is a BUG of new AMD AMF -> has to be fixed -> when 18 or 20 you save bitrate for high-movement scene in h264 // maxQP 51 looks bad -> so i stick using 42 (as this wont produce peaks even on high movement scenes in 720p when min 3000kbps)
6 - GOP 15 is recommended for YT when rec/stream in 30 FPS -> so would be nice if this wont be experimental anymore
7 - we need CABAC to handle CBR right with low Bitrate

will try hotfix now and send links to orginal files ;)

**Comment by Xaymar** [comment]
GOP Size and CABAC are not official VCE/AMF options. They are the result of reverse engineering. Do not use them.

**Comment by Benman2785** [comment]
same problem with 16.10.2 Hotfix
at 2:13 you can see it clearly drops frames -> would suck when i stream this to twitch
![stream-1477038232](https://cloud.githubusercontent.com/assets/21282980/19592225/0cae825e-977b-11e6-8842-9c0d25b7fbff.jpg)
[stream-1477038232.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/543895/stream-1477038232.txt)
http://benmanshafen.de/pics/OBS/Xaymar/stream-1477038232.flv (150mb)

**Comment by Benman2785** [comment]
with simple:
Bitrate 3500
CustomBuffer 116
FillerData Enabled
MemoryType DX11
Compute Type OpenCL
no custom GOP
CABAC default

still same problem - and it also drops frames now (when high peak occure) while streaming

![stream-1477039980](https://cloud.githubusercontent.com/assets/21282980/19592785/998f9972-977d-11e6-99cc-b0d59e75be68.jpg)
[stream-1477039980.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/543919/stream-1477039980.txt)
http://benmanshafen.de/pics/OBS/Xaymar/stream-1477039980.flv (130mb)

also noticed 1% more CPU load on average and my GPU also has more load -> peaks to 100% and wont hold Boost on everytime (what she did with advanced settings)

**Comment by Benman2785** [comment]
tested with old game - peak has nothing to do with high load -> as i said before it occures when nearly black screen with no movement -> then FillerData bugs and result in high peak - and now with 16.10.2 in dropped frames

![stream-1477041730](https://cloud.githubusercontent.com/assets/21282980/19594041/a3fe4218-9783-11e6-827f-c2f2e01e36e9.jpg)
http://benmanshafen.de/pics/OBS/Xaymar/stream-1477041730.flv (201mb)

**Comment by MikhailAMD** [comment]
The fix for filler data bug is in testing. I am trying to push it into the earliest possible release. Stay tuned.

**Comment by Benman2785** [comment]
still persists in 16.10.3

after install and reboot i could do it once without bug -> now it always bugs (ever) since

**Comment by MikhailAMD** [comment]
I will send a note when the fixes are available.

**Comment by Xaymar** [comment]
For tracking purposes, I'll keep this open.

**Comment by Xaymar** [comment]
I have updated the original report with more information. I'm not sure why, but Filler Data seems to be broken on my R9 285 again with driver 16.10.3, but that might just be a temporary problem.

**Comment by Xaymar** [comment]
Both CBR and VBR seem to be broken completely in 16.10.3 now. I will need additional people to test, but right now AMF encoding is pretty much useless except for recording - and even there it seems to start showing issues with random permanent encoding freezes until reboot.

**Comment by Xaymar** [comment]
16.10.3 seems to be the the Driver that breaks CBR on some cards again. I have implemented all the changes suggested in the VBR issue too but they had little effect here.

Result: 20mb/s instead of the set 3500kb/s, Filler Data is being ignored again.

* Log: http://cdn.xaymar.com/private/2016/11/2016-11-03%2018-21-18.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-03_18-21-26.mkv

**Comment by MikhailAMD** [comment]
The fix should be in the release hot fix driver: 16.11.1
http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-Edition-16.11.1-Release-Notes.aspx

**Comment by Xaymar** [comment]
Still having the issue with it not using the limits I gave it. Could you verify if this is the correct order I should be applying the settings in? I can't seem to figure out why it doesn't work.

- AMF_VIDEO_ENCODER_USAGE = AMF_VIDEO_ENCODER_USAGE_TRANSCONDING
- AMF_VIDEO_ENCODER_PROFILE = 100
- AMF_VIDEO_ENCODER_PROFILE_LEVEL = 52
- AMF_VIDEO_ENCODER_MAX_LTR_FRAMES = 0
- AMF_VIDEO_ENCODER_FRAMESIZE = (1920,1080)
- AMF_VIDEO_ENCODER_FRAMERATE = (60,1)
- AMF_VIDEO_ENCODER_SCANTYPE = AMF_VIDEO_ENCODER_SCANTYPE_PROGRESSIVE
- AMF_VIDEO_ENCODER_QUALITY_PRESET = AMF_VIDEO_ENCODER_QUALITY_PRESET_QUALITY
- L"CABACEnable" = 1

Init() gets called here.

- AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD = AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_CBR
- AMF_VIDEO_ENCODER_TARGET_BITRATE = 3500000
- AMF_VIDEO_ENCODER_PEAK_BITRATE = 3500000
- AMF_VIDEO_ENCODER_FILLER_DATA_ENABLE = true
- AMF_VIDEO_ENCODER_MIN_QP = 0
- AMF_VIDEO_ENCODER_MAX_QP = 51
- AMF_VIDEO_ENCODER_VBV_BUFFER_SIZE = 58333
- AMF_VIDEO_ENCODER_INITIAL_VBV_BUFFER_FULLNESS = 64
- AMF_VIDEO_ENCODER_RATE_CONTROL_SKIP_FRAME_ENABLE = false
- AMF_VIDEO_ENCODER_ENFORCE_HRD = true
- AMF_VIDEO_ENCODER_IDR_PERIOD = 60
- AMF_VIDEO_ENCODER_DE_BLOCKING_FILTER = true
- AMF_VIDEO_ENCODER_B_PIC_PATTERN = 3
- AMF_VIDEO_ENCODER_B_REFERENCE_ENABLE = true
- AMF_VIDEO_ENCODER_B_PIC_DELTA_QP = 0
- AMF_VIDEO_ENCODER_REF_B_PIC_DELTA_QP = 0
- AMF_VIDEO_ENCODER_MOTION_HALF_PIXEL = true
- AMF_VIDEO_ENCODER_MOTION_QUARTERPIXEL = true

* Log: [2016-11-04 10-16-19.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/571073/2016-11-04.10-16-19.txt)
* Video is slightly too large for an upload (54.4mbit/s, 70mb)

**Comment by MikhailAMD** [comment]
Parameters and log look correct. I will be able to do the tests on Monday.
Two questions for now:
1. To confirm: did you get 54 MBits stream with 3.5 MBit setting?
2. Please verify that you don't have performance delays in CPB mode that we saw before. 
Just out of curiosity: can you try the same with B-frames disabled?
Thanks,

**Comment by Xaymar** [comment]
1. Yup, I got a 54.4mbit/s stream with 3.5mbit setting. Same thing happens with VBR, only CQP and VBR_LAT seem to still work fine.
2. I will need to wait for the RX to arrive before I can test that. On VCE3 I had no performance issues/Filler Data weirdness.

I will test with B-Pictures disabled once I have fixed some issues with Direct3D11 initialization.

**Comment by Xaymar** [comment]
### Test with BPictures at 3

* Log: http://cdn.xaymar.com/private/2016/11/2016-11-04%2015-12-01.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-04_15-12-09.7z

### Test with BPictures at 0, BReference Disabled

* Log: http://cdn.xaymar.com/private/2016/11/2016-11-04%2015-12-36.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-04_15-14-43.7z

**Comment by MikhailAMD** [comment]
CBR developer provided following comment:
in the log:
VBV BuffSize:   58333
Vbv_buffer_size should be no less than peak_bitrate/frame_rate (3500000/60=58333.33333), please suggest them try vbv_buffer_size = 58400

**Comment by Xaymar** [comment]
### Test - B-Pictures Disabled, VBV Buffer Size at 58400
* Log: http://cdn.xaymar.com/private/2016/11/2016-11-04%2016-11-31.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-04_16-12-45.7z

### Test - B-Pictures Disabled, VBV Buffer Size at 3500000
* Log: http://cdn.xaymar.com/private/2016/11/2016-11-04%2016-13-45.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-04_16-14-12.7z

I don't understand why this happens. The log file shows the proper settings being applied, but for some reason they don't end up being used. Some users report that an older plugin version (1.3.3.1, which had set things wrongly) works though I find that to be rather strange.

**Comment by Xaymar** [comment]
Further reading through the logs sent in by users and produced by me reduced a weird inconsistency:

```
18:12:30.898: [VCEEncoderTrace]     Info: SetProperty TargetBitrate:3500000
18:12:30.898: [VCEEncoderTrace]     Info: SetProperty PeakBitrate:3500000
18:12:30.898: [VCEEncoderTrace]     Info: SetProperty FillerDataEnable:true
18:12:30.898: [VCEEncoderTrace]     Info: SetProperty MinQP:1
18:12:30.898: [VCEEncoderTrace]     Info: SetProperty MaxQP:51
18:12:30.898: [VCEEncoderTrace]     Info: SetProperty RateControlMethod:1
18:12:30.898: [VCEEncoderTrace]     Info: SetProperty VBVBufferSize:100705
18:12:30.898: [VCEEncoderTrace]     Info: SetProperty InitialVBVBufferFullness:64
18:12:30.898: [VCEEncoderTrace]     Info: SetProperty RateControlSkipFrameEnable:false
18:12:30.899: [VCEEncoderTrace]     Info: SetProperty EnforceHRD:true

...

18:12:30.902: [VCEEncoderTrace]     Info: <--------------------- Rate Control Params(-1) ----------------------------->
18:12:30.902: [VCEEncoderTrace]     Info:     RateCtrlMethod: 3
18:12:30.902: [VCEEncoderTrace]     Info:     Target bitrate: 3500000
18:12:30.902: [VCEEncoderTrace]     Info:     Peak bitrate:   3500000
18:12:30.903: [VCEEncoderTrace]     Info:     RCFrameRateNum: 60
18:12:30.903: [VCEEncoderTrace]     Info:     RCFrameRateDen: 1
18:12:30.903: [VCEEncoderTrace]     Info:     GOPSize:        0
```

Somehow the Rate Control Method is not being set properly. The exact reason (and why it only works on certain systems) still eludes me.

**Comment by MikhailAMD** [comment]
depend on which part of tracing you are looking rate control is in AMF enum or in internal enum, They have different values. 
AMF CQP = 0 internal = 0
AMF CBR  = 1 internal = 3.
AMF VBR_PEAK = 2 internal = 4   
AMF VBR_LAT = 3 internal = 6
AMF logging is here:
 Info: SetProperty RateControlMethod:1
Internal values are reported just before sending them to the driver after this line.
Info: <--------------------- Rate Control Params
Compare what you set and what driver get in one log.

**Comment by Xaymar** [comment]
Log file matches what you said:

```
20:13:45.457: [AMF Encoder]   Method: Constant Quantization Parameter (CQP)
20:13:45.523: [VCEEncoderTrace]     Info:     RateCtrlMethod: 4
20:13:45.523: [VCEEncoderTrace]     Info: SetProperty RateControlMethod:0
20:13:45.624: [VCEEncoderTrace]     Info:     RateCtrlMethod: 0

20:13:53.545: [AMF Encoder]   Method: Constant Bitrate (CBR)
20:13:53.558: [VCEEncoderTrace]     Info:     RateCtrlMethod: 4
20:13:53.559: [VCEEncoderTrace]     Info: SetProperty RateControlMethod:1
20:13:53.660: [VCEEncoderTrace]     Info:     RateCtrlMethod: 3

20:14:00.628: [AMF Encoder]   Method: Peak Constrained Variable Bitrate (VBR)
20:14:00.690: [VCEEncoderTrace]     Info:     RateCtrlMethod: 4
20:14:00.690: [VCEEncoderTrace]     Info: SetProperty RateControlMethod:2
20:14:00.792: [VCEEncoderTrace]     Info:     RateCtrlMethod: 4

20:14:08.114: [AMF Encoder]   Method: Latency Constrained Variable Bitrate (VBR_LAT)
20:14:08.127: [VCEEncoderTrace]     Info:     RateCtrlMethod: 4
20:14:08.128: [VCEEncoderTrace]     Info: SetProperty RateControlMethod:3
20:14:08.229: [VCEEncoderTrace]     Info:     RateCtrlMethod: 6
```

Testing with the above revealed that all files but CQP are perfectly identical in terms of bitrate and setup. I will test with an earlier driver tomorrow and see if it is a regression in 16.10.3 and up, it's quite late here.

* Log: http://cdn.xaymar.com/private/2016/11/2016-11-04%2020-13-36.txt

**Comment by MikhailAMD** [comment]
Please note than not all rate control modes are available on all HW. I will ask Monday for a table but you can get property description from AMF interface GetPropertyInfo() and use pEnumDescription to enumerate what is available on active HW. 
I checked, currently AMF does not validate vs available rate control modes and I plan to add this in the future.

**Comment by Xaymar** [comment]
Afaik CBR and VBR are available on all VCE 3 and 2 cards, as they worked fine with an older driver (16.9.2 + R9 285 = CBR that worked, it was only the RX 4xx series having trouble with CBR). Even VCE 1 cards and APUs had 0-issues with this until now.
I will be waiting for your reply on monday and try to implement the GetPropertyInfo thing tomorrow.

**Comment by MikhailAMD** [comment]
I understand. Work from home today. Monday will test and bring rate control guy if needed.

**Comment by Xaymar** [comment]
```
[AMF Encoder] Name: RateControlMethod
[AMF Encoder] Desc: Rate Control Method
[AMF Encoder] Type: 2
[AMF Encoder] Content Type: 0
[AMF Encoder] Min Value Type: 0
[AMF Encoder] Min Value Int64: 0
[AMF Encoder] Max Value Type: 0
[AMF Encoder] Max Value Int64: 0
[AMF Encoder] Default Value Type: 2
[AMF Encoder] Default Value Int64: 2
[AMF Encoder] Constant QP 0
[AMF Encoder] CBR 1
[AMF Encoder] Peak constrained VBR 2
[AMF Encoder] Latency constrained VBR 3
```

Quick & Dirty implementation, GetPropertyInfo and pEnumDescription show that all of them are there.

**Comment by Xaymar** [comment]
Some people report that it works on VCE2 cards while others report that it's completely random if it works or not. This couldn't get any more random if it tried to, could it?

**Comment by Xaymar** [comment]
### Settings Tested
* 1920x1080, 30 FPS
* Quality Preset: Balanced
* Profile: High 5.2
* Rate Control Method: CBR
* Target Bitrate: 3500kbit/s
* Min/Max QP: 0/51
* VBV Buffer Size: 117kbit (64 Fullness, 100%)
* Filler Data: Enabled
* Frame Skipping: Disabled
* Enforce HRD Compatibility: Enabled
* IDR Period: 60
* B-Picture Pattern & Reference: 0, Disabled
* Deblocking Filter: Enabled
* Motion Estimation: Half, Quarter
* CABAC: Disabled
* Memory Type: "Host"
* OpenCL: Disabled

### Driver 16.9.2:
* Plugin Version 1.3.3.1 - 16.3 mbit/s
* Plugin Version 1.4.1.1 - 16.6 mbit/s

Will update with further test results after upgrading drivers again.

**Comment by Xaymar** [comment]
I get similar results with VCEEncoderD3D:

```
>VCEEncoderD3D.exe -FRAMES 600 -HEIGHT 1080 -WIDTH 1920 -OUTPUT test.h264 -Usage TRANSCODING -Profile High -ProfileLevel 42 -QualityPreset Quality -FrameRate 60,1 -FillerDataEnable true -TargetBitrate 20000000 -RateControlMethod CBR
DX9: List of adapters:
          0: Device ID: 6939 [AMD Radeon R9 200 Series]
DX9 : Chosen Device 0: Device ID: 6939 [AMD Radeon R9 200 Series]
Start: 1 threads

 Average (Max, fr#) Encode Latency: 10.4 ms (22.7 ms frame# 0)
 Average (Max) Frame size: 1771 bytes (5069 bytes)
 Frames processed: 600 Frame process time: 10.4ms FPS: 95.8
 Average FPS: 95.8 Combined FPS: 95.8

D:\Software\SDK\AMD-AMF\amf\bin\vs2013x32Debug
> ffmpeg -i test.h264 -codec:v copy -codec:a copy -y "test.mp4"
```

Resulting file after file format conversion:

```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Format settings, GOP                     : M=2, N=15
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 10 s 24 ms
Bit rate                                 : 848 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 59.859 FPS
Minimum frame rate                       : 25.000 FPS
Maximum frame rate                       : 60.000 FPS
Original frame rate                      : 60.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.007
Stream size                              : 1.01 MiB (99%)
Color range                              : Limited
```

Raw File: http://cdn.xaymar.com/private/2016/11/test.h264

I am out of ideas and things to test now, this problem doesn't make any sense to me. CBR and VBR worked when I had 16.10.2 installed, then I upgraded to 16.11.1 and things broken, but downgrading back to 16.10.2 does not fix the problem.

**Comment by MikhailAMD** [comment]
I tested most of GPUs I have with this portable OBS setup. It was really easy to use.
I tested the latest public driver: 16.11.2 and I cannot reproduce CBR problem. All GPUs I tried produce 3.5 Mbit stream. I tried: Tonga (R9 285), Ellesmere (RX 480), Fiji (R9 Nano). 
With Hawaii (R9 390) VCE plug-in failed to start recording. The reason is that 390 doesn't support 5.2 profile level and the property failed to set. 5.2 level is needed for 4K only. For 1080p it should be 4.2. Check table for levels here: https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC. This should be easy to fix.

I repeated your command line for VCEEncoderD3D.exe on Tonga (R9 285)  and got 25 MB file - not 1 MB you posted.

All this points to the driver installation. 
One thing I would like to confirm: sometimes driver installation cannot cleanly downgrade. There is a cleanup tool that should help: http://support.amd.com/en-us/kb-articles/Pages/AMD-Clean-Uninstall-Utility.aspx
In any case it is recommended to check device manager and uninstall video driver versions one by one from there with deleting driver files option till you see Microsoft Basic Display (Adapter). And then reboot and install the driver you want.  
Please try clean install of 16.11.1 or 16.11.2 (they are identical for VCE).

**Comment by Xaymar** [comment]
I tried the clean install steps you provided, however the results are still the same. CBR & VBR both ignore anything I tell it to do and it's unfortunately not just me that has this issue. I have also tried disabling the Intel GPU in the CPU and removing the drivers for those to see if that would help, that also didn't help.

I've asked Kytos (he also has this issue) to test with a clean Windows install, I'll hear back from him tomorrow afternoon/evening.

One question, the drivers don't reflash the GPU hardware right? I don't know how AMD hardware works internally, so this might sound stupid to someone who does.

**Comment by MikhailAMD** [comment]
Which OS do you have, is it Win10 with RS1 (Redstone) or without? 
In general, driver will check and update VCE firmware during boot time if needed. Depend on RS1 or not RS1 the firmware is located in different folder. I don't think Intel GPU can interfere. Can I access your computer via TeamViewer and check few things? If so let's contact tomorrow via Skype.

**Comment by Xaymar** [comment]
I have Windows 10 Pro 64-Bit with Anniversary Update "Redstone 1", winver reports Version 1607 (OS Build 14393.351)".

> Can I access your computer via TeamViewer and check few things? If so let's contact tomorrow via Skype.

Sure, I have TeamViewer installed now.

**Comment by Xaymar** [comment]
With the help of @MikhailAMD we've found a way to fix one of the problems: It was a stale driver install/uninstall that didn't go through completely, possibly from Windows Update or similar. After removing this stale driver, VCE encoding worked as expected again.

### Steps for a fully clean Driver install
1. Uninstall the AMD Driver in Windows, make sure Device Manager says "Microsoft Basic Display Adapter"
2. Reboot to Safe Mode (using DDU or any other means)
3. If DDU was used, let it remove the driver stuff without restarting.
4. Navigate to C:\Windows\System32\DriverStore\FileRepository in Explorer
5. Delete any folders called c030*.inf* (* being anything) (there should only be one or two if DDU and Uninstall worked)
6. Reboot to System
7. Install latest AMD driver normally
8. Reboot

As for the bitrate going way over the targetted bitrate, that is due to limits on how much a frame can be compressed. Enabling RateControlSkipFrame may help here.

Solution: Don't trust your driver to be actually uninstalled.

**Comment by Benman2785** [comment]
with new driver still persists -> only fixed when i set minQP to 0 or 1 -> fix that please

**Comment by Xaymar** [comment]
Can't confirm that Benman. I have been testing all the reported issues on both my R9 285 and the RX 480 that Mikhail sent me and have only noticed one issue with VBV Buffer Size, which also doesn't happen all the time (1 in 10 chance that it happens).

**Comment by Benman2785** [comment]
then pls set minQP to 20 (to reduce load on GPU) and try FillerData -> you will see its bugged

**Comment by wazerstar** [comment]
@Xaymar I contacted the DDU developer, he will look into ASAP why the c030 files/folders are not deleted while using his tool, and possible make an update ;)

**Comment by Xaymar** [comment]
> @Benman2785: then pls set minQP to 20 (to reduce load on GPU) and try FillerData -> you will see its bugged

You don't reduce the load on the GPU by increasing Min QP, you only reduce PCI-E bandwidth requirements. And most often your frames will never go below a QP of 18 anyway. The only thing you tell AMF that way is "fuck my quality up, i want as little data as possible" which only works by compressing more (which has a negative impact on performance). To quote what Mikhail told me: AMF does not make any adjustments to user settings - errors in the configuration will be used as is.

I used your own tool to "analyze" a recorded file, the bitrate is completely fine:
![image](https://cloud.githubusercontent.com/assets/437395/20531820/3475e2ca-b0d8-11e6-8ef6-0988e5ea9693.png)
Log: https://gist.github.com/095dae1d96cb1173050877e8b24e702d

> @wazerstar: @Xaymar I contacted the DDU developer, he will look into ASAP why the c030 files/folders are not deleted while using his tool, and possible make an update ;)

That's great to hear.
