### ISSUE TITLE
[Unsupported][Discussion][Arch Linux]: AMF encoding with VCN4 (RX 7900 XTX) not working with current linux-firmware

### ISSUE THREAD

**Issue by RiantAnda** [GPUOpen-LibrariesAndSDKs/AMF#392]
**Describe the bug**
When I try to run FFMPEG with AMF, it is not working.
The error message is
`[h264_amf @ 0x55ab62cc2cc0] CreateComponent(AMFVideoEncoderVCE_AVC) failed with error 1`
`[vost#0:0/h264_amf @ 0x55ab62cc19c0] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height`
My system has the latest linux-firmware version `linux-firmware-20230404`
When I downgrade to `linux-firmware-20221214`, the issue is gone. 
This can be achieved by simply replacing `vcn_4_0_0.bin` in `/usr/lib/firmware/amdgpu/`.

**To Reproduce**
1. Run FFMPEG on a system with `linux-firmware-20230117` or newer. 
E.g. `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_pro_icd64.json ffmpeg -hwaccel auto -vaapi_device /dev/dri/renderD128 -i input.mp4 -c:v hevc_amf -rc 1 -b:v 8M output_hevc.mp4` 
2. The above command should not work and return the error described above.
3. Downgrade linux-firmware to `linux-firmware-20221214`, then reboot the system.
4. Run FFMPEG again, transcoding should work without any error messages.

**Setup (please complete the following information):**
 - OS: Arch Linux
 - Driver Version: 22.40
 - GPU RX 7900 XTX
 - Which component has the issue: Encoder, either in vcn_4 firmware or driver

**Expected behavior**
AMF encoding should work with the latest linux-firmware

This issue is also reported by others, see https://github.com/Ashark/archlinux-amdgpu-pro/issues/85

**Comment by UFeindschiff** [comment]
Can confirm the same behavior with the RX 7900XT.

Why not ship firmware required for AMF as part of the proprietary driver/software package like nvidia does to ensure compatibility? As it is right now updating one component or the other will break functionality, which is fairly bad. Getting everything to work with a RX 7900XT is a huge headache right now. For example it was just pure chance that I stumbled across this report after trying to get AMF to work for several hours.

**Comment by MikhailAMD** [comment]
All driver components including AMF runtime, VCN firmware, Vulkan, OGL, VAAPI and many other drivers are delivered as a one install script, all coming from a single repo and compatibility is maintained. In the essence, it is a single package. please check AMD drivers page on www.amd.com. But this is true for the supported distros. Here it is an attempt to install the driver and components on unsupported Arch distro. I can provide some informal advice like above but no commitment for support.

**Comment by mesmerx** [comment]
as a maintainer of the arch package its hard to put dependencies on the package for firmware as its only impacting the 7000 series,  we put in the wiki a information about firmware vcn and the version that is working there, but maybe we can generate a new package for 7000 series with this constrain, idk, its hard because it can be offsync very easy, sometimes its better to wait and this is fixed with driver updates (like happened for 6000 series in the past)

**Comment by RiantAnda** [comment]
What I personally do not understand, is the fact that somebody at AMD released a new vcn4 linux-firmware in January, but 4 month later, still no compatible linux driver is available by AMD. Why? 
Is there no release planning? 
Why not release a driver that is able to handle current and upcoming firmware, then release new linux-firmware?
I mean this entirely in the hand of AMD, both driver and firmware are proprietary software.

**Comment by mesmerx** [comment]
i think the 5.5.2 fixed the need for the linux-firmware-git (at least for me)

**Comment by RiantAnda** [comment]
Arch upgraded linux-firmware to v20230625 on June 26. Since then the issue is gone for me.

The question is, when will AMD upgrade one of the components and we have not matching driver/firmware again?
It would be nice if they could work out some strategy, like driver backward/forward compatibility for firmware.

**Comment by RiantAnda** [comment]
The issue is back with linux-firmware-20231030.
Any driver release I tried gave me:
`VCN FW Encode interface version=1.12, expected version=1.11`

Does anybody know if a driver compatible with v1.12 has been released yet?

**Comment by rhutsAMD** [comment]
Closing this issue as Arch Linux is an unsupported distro and changing the title to reflect that. While the ticket is closed, please feel free to continue to use it for any residual discussions or updates.

**Comment by mesmerx** [comment]
from time to time (from nature of rolling release of arch) the firmware and the driver get out of sync, its expected and not a error overall, right now for 5.7.2 and 5.7.3 it seems to work with latest firmware :)

i advise to not post this type of problem is this github because its not a problem for this project directly and i dont see anything they can do, int he arch we try to mark the firmware needed to work (when one is found) 

@rhutsAMD  thx to not close this for discussion
