### ISSUE TITLE
[Bug]: <stream is not FLV 1.1 compatible>

### ISSUE THREAD

**Issue by Benman2785** [GPUOpen-LibrariesAndSDKs/AMF#460]
**Describe the bug**
i can stream to my nginx with rtmp
i can download and watch the flv with vlc - also when live
when using AMF h264 instead of x264 with OBS i only get audio but no video output from jwplayer (swf)
but i can download the saved flv and watch them via VLC or upload to youtube

have in mind that [ruffle](https://github.com/ruffle-rs/ruffle) has not implemented flv playback yet - but given that RTMP Enhanced also supports h265 and AV1 it is given that they will implement all major 3 codecs - and it will be used for playback on some peoples website

**To Reproduce**
1.) nginx + [nginx-http-flv-module](https://github.com/winshining/nginx-http-flv-module)
2.) stream and watch livestream with player.swf from jwplayer
3.) you only hear audio but have no video

**Setup (please complete the following information):**
 - OS: Win11
 - Driver Version [24.1.1]
 - GPU [RX 7700 XT]
 - Which component has the issue [Encoder]

**Debug Log (please upload or paste):**
```
no log - as its intended but wrong
```

**Expected behavior**
a stream that is flv 1.1 compatible // that plays in jwplayer on swf/flash

**Screenshots**

**Additional context**
if needed i can provide an example - have the files on my server

**Comment by Benman2785** [comment]
here you have your files:
https://hoffmeister.li/streamdl/x264_CPU.flv
https://hoffmeister.li/streamdl/h264_AMF.flv

here is the "JW Player" via Flash
https://hoffmeister.li/tv/streamjw.html
here is the swf
https://hoffmeister.li/flash-games/jwplayer/player.swf

so x264 works fine but h264 does not

please keep notice that i later use Ruffle to show the swf - yet the media playback is only implemented for MP3 as of now

**Comment by DimkaTsv** [comment]
Weird... 
When i try to play it through normal players (not flash ones), everything is fine.
But when i tried to check them through media analyzer, i saw peculiar difference (sorry for half-assed tool usage).

x264 CPU sample has such hierarchy:
```
FLV file
-- File Info
-- Audio Stream
-- -- AAC Raw
-- Video Stream
-- -- H.264/AVC
```
![image](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/9446187/7b0e2157-1e5a-418b-b36f-075d31d7381d)

But when i try to check AVC AMF sample, it has completely different structure.
```
Elementary
-- H.264/AVC
```
![image](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/9446187/873869b3-1663-4f19-b61f-46b692a30238)

I don't have capability to properly debug issue (random user and stuff). But i am providing information i noticed.

**Comment by Benman2785** [comment]
https://hoffmeister.li/tv/vcejw.html - here is https://drive.google.com/file/d/1A2d-zehNnjxEtnFQKLbg4BL7XlBsXopD/view?usp=sharing - again you only have audio but no video :/

so far you need to use an old browser with flash installed - as ruffle has no video decoder built in (as of now)

**Comment by MikhailAMD** [comment]
> here you have your files: https://hoffmeister.li/streamdl/x264_CPU.flv https://hoffmeister.li/streamdl/h264_AMF.flv
> 
> here is the "JW Player" via Flash https://hoffmeister.li/tv/streamjw.html here is the swf https://hoffmeister.li/flash-games/jwplayer/player.swf
> 
> so x264 works fine but h264 does not
> 
> please keep notice that i later use Ruffle to show the swf - yet the media playback is only implemented for MP3 as of now

The only problem/warning I see in the AMF FLV stream is that primary color in VUI header is set to zero. It was fixed but not yet in the public driver.

**Comment by MikhailAMD** [comment]
@DimkaTsv  TranscodeHW command line gets bitrate in bits. 600Kbit is 600000 etc.

**Comment by DimkaTsv** [comment]
> @DimkaTsv TranscodeHW command line gets bitrate in bits. 600Kbit is 600000 etc.

Oh, oops. My bad. But it still compresses to values way below 6000 kbit/s even if i use cbr 6'000'000
If you look at resulting file metadata (below), then bitrate of video thread will be reported as 5859, but overall bitrate in "General" section is only 782 kb/s. As well as file size being not around 15 MB, but 2 MB instead.  Filler data was enabled. 

```
General
Complete name                  : C:\Users\DimkaTsv\Downloads\x264_CPU_processed.flv
Format                         : Flash Video
File size                      : 1.99 MiB
Duration                       : 21 s 366 ms
Overall bit rate               : 782 kb/s
Frame rate                     : 60.120 FPS
Writing application            : Lavf60.3.100

Video
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : Main@L4.2
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 4 frames
Format settings, GOP           : M=1, N=30
Codec ID                       : 7
Duration                       : 21 s 366 ms
Bit rate                       : 5 859 kb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 60.120 FPS
Original frame rate            : 60.000 FPS
Standard                       : Component
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.047
Stream size                    : 14.9 MiB
Color range                    : Limited
Matrix coefficients            : BT.709

Audio
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : 10-2
Duration                       : 21 s 358 ms
Bit rate                       : 125 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 44.1 kHz
Frame rate                     : 43.066 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 326 KiB (16%)
```


Is there some frame skip/duplication going on by default? Because i saw that VCEEnc reports 
`Others:        skipframe:on deblock`. 
And there is option to enabled it with flag --skip-frame, but only enable it. There is no "force disable" option, and it does seem to be enabled all the time by default.

**Comment by MikhailAMD** [comment]
@DimkaTsv  Let's not mix up issues. For bitrate - please provide source, command line, driver version and HW in a separate topic.

**Comment by Benman2785** [comment]
@DimkaTsv 

1. + 3. are correct
for 2. = i stream via OBS on my own server that runs nginx with nginx-http-flv-moudle

for 1. i am working with ruffle team
for 3. here is why i wrote you to AMD :)

if you want to see the problem yourself (with old browser and flash installed):

https://hoffmeister.li/tv/stream2.html = video and audio are fine (https://hoffmeister.li/tv/test2.flv)
https://hoffmeister.li/tv/stream3.html = only audio is played (https://hoffmeister.li/tv/test3.flv)

**Comment by Benman2785** [comment]
has something moved in the time?

i will ask again after easter - enjoy the holidays

**Comment by Benman2785** [comment]
not fixed in 24.3.1

**Comment by DimkaTsv** [comment]
> not fixed in 24.3.1

In 24.3.1 AMF runtime version didn't change compared to 24.2.1, so it was reasonable to assume that issue is not fixed.

**Comment by Benman2785** [comment]
did you atleast found the bug so that it can be fixed? :)

**Comment by MikhailAMD** [comment]
Few things to note:
1. AMF version changes when API is extended or with every major release. Even if version was not changed each released driver usually have some fixes or improvements, so it is worth to check the latest.
2. In the streams provided I see one problem in VUI header produced by AMF encoder: color_primaries are set to zero. This issue has been fixed recently.
3. Beside 2, the stream is fully compliant with H264 specs (as best as analyzer could tell).
4. Comparing the files here is the list of differences AMF vs x264: 
SPS:
- profile_level 42 vs 32 - can be changed in AMF parameters 
- constraint_set5_flag 1 vs 0 - 1- that B slice types are not present in the coded video sequence.
- log2_max_pic_order_cnt_lsb_minus4 1 vs 2 - should not matter
- pic_width_in_mbs_minus1	119 vs 79 - different resolution 1920 v s1280
- pic_height_in_map_units_minus1	67 v 44 - different resolution 1080 vs 720
VUI header:
- aspect_ratio_idc 255 (Extended_SAR) vs 1 - see next two
- sar_width 1 vs not present - AMF aspect is 1x1
- sar_height 1 vs not present 
- video_format 0 (component) vs 5 (Unspecified video format) 
- colour_primaries 0 vs 1 - fixed
- log2_max_mv_length_horizontal	16 vs 11 - different resolution
- log2_max_mv_length_vertical	16 vs 11 - different resolution

**Comment by Benman2785** [comment]
both videos have the same resolution - so i am not sure about:
sar_width 1 vs not present - AMF aspect is 1x1
sar_height 1 vs not present
pic_width_in_mbs_minus1 119 vs 79 - different resolution 1920 v s1280
pic_height_in_map_units_minus1 67 v 44 - different resolution 1080 vs 720
log2_max_mv_length_horizontal 16 vs 11 - different resolution
log2_max_mv_length_vertical 16 vs 11 - different resolution

**Comment by Benman2785** [comment]
here is a new file with 24.4.1
http://benmanshafen.de/streamdl/h264_AMF_2.flv

still doesnt work

**Comment by MikhailAMD** [comment]
I re-checked, colour_primaries fix is not in the public driver yet, but it was fixed and coming. Apologies,
The rest for the new clip is the same as for test3.flv
Even MediaInfo shows different resolutions for the files. I am only guessing but could the resolution mismatch between OBS and the server cause the problem?

**Comment by Benman2785** [comment]
hehe the reason for this is because i made new files with "everything" as similar as possible:

http://benmanshafen.de/streamdl/h264_AMF.flv (24.3.1)
http://benmanshafen.de/streamdl/h264_AMF_2.flv (24.4.1)
http://benmanshafen.de/streamdl/x264_CPU.flv (x264 via OBS)

please look into x264_CPU.flv and h264_AMF.flv and try to find reasons why the x264_CPU works with https://hoffmeister.li/tv/streamjw_ruffle.html and why h264_AMF does not work (it only plays audio but no video)

maybe colour_primaries fix will help - but we will see :)

please be aware that ruffle as of yet does not support jw_player playback as it cant handle the video; sofar i use the old Adobe Flash in my old K-Meleon Browser to check // i try to convince the guys from ruffle to implement rtmp_enhanced into ruffle = to allow AV1 streaming on my own (nginx based) streaming server :)

**Comment by Benman2785** [comment]
is the fix ready and when will it release? :)

**Comment by Benman2785** [comment]
thanks - i will test it this weekend :)

**Comment by Benman2785** [comment]
it still does not work :(
here is the latest AMF video: https://hoffmeister.li/streamdl/h264_24.6.1.flv

CBR 1080p@6000kbps AMF "Quality" "high" Max 4 B-Frames & 2s Keyframe Intervall

`ProfileLevel=42 MaxNumRefFrames=4 CABACEnable=true EnablePreAnalysis=true RateControlPreanalysisEnable=true RateControlSkipFrameEnable=false EnforceHRD=true FillerDataEnable=true AdaptiveMiniGOP=true EnableVBAQ=true DeBlockingFilter=true HalfPixel=true QuarterPixel=true HighMotionQualityBoostEnable=true MaxConsecutiveBPictures=3 BPicturesPattern=3 BReferenceEnable=true PALookAheadBufferDepth=41 PAFrameSadEnable=true PAPerceptualAQMode=1 PATemporalAQMode=1 PACAQStrength=2 PAHighMotionQualityBoostMode=0`

**Comment by Benman2785** [comment]
is there a way to manually force mime-type?
like: "MimeType=video/mp4" or "mime-type=video/x-flv"

**Comment by Benman2785** [comment]
any new info here?

**Comment by Benman2785** [comment]
i dont want to start nagging - but its still not fixed (i guess - since i use the AFMF2-beta)

**Comment by Benman2785** [comment]
can anyone give me an update - because until 24.9.1 it still does not work.
will try 24.10.1 now

**Comment by Benman2785** [comment]
as DimkaTsv showed (https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/460#issuecomment-1987107096 ): the file hiearchy is different - i suspect that this is the issue.
is this because of OBS or is this because of AMF?

**Comment by MikhailAMD** [comment]
Several topics are discussed here. Color issue should be fixed by now.  FLV - compatibility issue, please retest.
